apiVersion: v1
kind: Service
metadata:
  name: mongodborg0-lb
spec:
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodborg0
    app.kubernetes.io/name: mongodb
  ports:
    - name: "27017"
      port: 27017
      nodePort: 32017
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress-0
  labels:
    app: mongoexpress-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexpress-0
  template:
    metadata:
      labels:
        app: mongoexpress-0
    spec:
      containers:
        - name: mongoexpress-0

          #https://hub.docker.com/_/mongo-express
          image: mongo-express:0.54.0
          ports:
            - name: tp
              containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: "mongodborg0"
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "root"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "password"

---

apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-0-lb
spec:
  selector:
    app: mongoexpress-0
  ports:
    - name: "mongo-express"
      port: 8081
      nodePort: 30081
  type: LoadBalancer
